#!/bin/bash

# This script will runas the ubuntu user and yet needs sudo permissions on the /etc/cntlmc.conf file
# Due to the insane perl and sed calls needed to do regex substitutions in the files, is easier to inject these calls
# into a file and then sudo execute that rather than try and get the formatting right to run sudo on the calls directly
#
# 1. Push these commnds into a temp file
# 2. Make the file executable
# 3. Run the file with sudo privileges
# 4. Remove the file

temp_file=$(mktemp)
cat > $temp_file << 'EOL'
#!/bin/bash
echo "Setting up password for CNTLM authentication proxy"
echo
echo "Please enter your NTADMIN username (e.g. testuser1), followed by [ENTER]:"
read username
echo
echo "Please enter your password, followed by [ENTER]:"
read -s password
echo "Generating the configuration for CNTLM and injecting it into /etc/cntlm.conf"
temp_file=$(mktemp)
domain=$(cat /etc/cntlm.conf | grep Domain | awk '{print $2}')
password_hash=$(echo ${password} | cntlm -H -c ${temp_file} -d ${domain} -u ${username} | tail -n 3)

sed -i "s/^Username\(\s\+\).*$/Username\1${username}/g" /etc/cntlm.conf
perl -0777 -i.orig -pe 's/(# ---START PASSWORD BLOCK\n)[a-z|A-Z|\s|\d|\#|'\''|\,|\-|_]+\n(# ---END PASSWORD BLOCK\n)/$1'"${password_hash}"'\n$2/igs' /etc/cntlm.conf
rm $temp_file
EOL
chmod a+x $temp_file
sudo sh -c "$temp_file"
rm $temp_file