#!/bin/bash

echo "Setting up password for CNTLM authentication proxy"
exit 0

#^#\s---START\sPASSWORD\sBLOCK\n([a-zA-Z\s\n\d]+)#\s---END\sPASSWORD\sBLOCK$

#perl -0777 -pe 's/(# ---START PASSWORD BLOCK\n)[a-z|A-Z|\s|\d]+\n(# ---END PASSWORD BLOCK\n)/$1foobar\n$2/igs' test_regex